sequenceDiagram
  participant participant_assertKnownPermission as assertKnownPermission
  participant participant_createFakePermissionClient as createFakePermissionClient
  participant participant_createFakePermissionContext as createFakePermissionContext
  participant participant_createFakePermissionOperations as createFakePermissionOperations
  participant participant_createPermissionState as createPermissionState
  participant participant_isPermission as isPermission
  participant participant_normalizeSeed as normalizeSeed
  participant_createFakePermissionClient->>participant_createFakePermissionContext: createFakePermissionContext()
  participant_createFakePermissionContext->>participant_createPermissionState: createPermissionState()
  participant_createPermissionState-->>participant_createFakePermissionContext: return
  participant_createFakePermissionContext->>participant_normalizeSeed: normalizeSeed()
  participant_normalizeSeed->>participant_createPermissionState: createPermissionState()
  participant_createPermissionState-->>participant_normalizeSeed: return
  participant_normalizeSeed->>participant_assertKnownPermission: assertKnownPermission()
  participant_assertKnownPermission->>participant_isPermission: isPermission()
  participant_isPermission-->>participant_assertKnownPermission: return
  participant_assertKnownPermission-->>participant_normalizeSeed: return
  participant_normalizeSeed-->>participant_createFakePermissionContext: return
  participant_createFakePermissionContext-->>participant_createFakePermissionClient: return
  participant_createFakePermissionClient->>participant_createFakePermissionOperations: createFakePermissionOperations()
  participant_createFakePermissionOperations-->>participant_createFakePermissionClient: return
