sequenceDiagram
  participant participant_useContext as useContext
  participant participant_usePermissions as usePermissions
  participant_usePermissions->>participant_useContext: useContext()
  participant_useContext-->>participant_usePermissions: return
